# Generated by Django 3.2 on 2021-04-22 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='ROG Club')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('nick_name', models.CharField(max_length=50, verbose_name='Никнейм')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата посещения')),
                ('time', models.IntegerField(max_length=3, verbose_name='Кол-во минут')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='neoclub.player', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Посещения',
            },
        ),
        migrations.CreateModel(
            name='Computers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Номер компьютера')),
                ('characteristics', models.TextField(blank=True, null=True, verbose_name='Характеристика')),
                ('hall', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='neoclub.hall', verbose_name='Зал')),
                ('visit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neoclub.visit', verbose_name='Посещение')),
            ],
            options={
                'verbose_name': 'Компьютер',
                'verbose_name_plural': 'Компьютеры',
            },
        ),
    ]
