# Generated by Django 3.2 on 2021-04-22 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neoclub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computers',
            name='visit',
        ),
        migrations.AddField(
            model_name='visit',
            name='computers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neoclub.computers', verbose_name='Компьютер'),
        ),
    ]
